/* *
 * We create a language strings object containing all of our strings.
 * The keys for each string will then be referenced in our code, e.g. handlerInput.t('WELCOME_MSG').
 * The localisation interceptor in index.js will automatically choose the strings
 * that match the request's locale.
 * */

module.exports = {
    en: {
        translation: {
            SKILL_NAME: 'my sponsor says',
            GET_FACT_MESSAGE: 'my sponsor says: ',
            HELP_MESSAGE: 'You can say ask my sponsor says about meetings in a city for In Person Meetings today',
            HELP_REPROMPT: 'What can I help you with?',
            FALLBACK_MESSAGE: 'The my sponsor says skill can\'t help you with that.  It can help you discover facts about recovery if you say share some recovery. What can I help you with?',
            FALLBACK_REPROMPT: 'What can I help you with?',
            ERROR_MESSAGE: 'Sorry, there was an error, Please try again.',
            STOP_MESSAGE: 'Goodbye!',
            FACTS:
            [
                'Do the footwork.',
                'Don\'t call me after you drink; call me before you drink.',
                'Don\'t let people rent space in your head.',
                'Don\'t think, don\'t drink, and go to meetings.',
                'Easy does it.',
                'F.E.A.R. - False Evidence Appearing Real.',
                'Fake it \'till you make it.',
                'Feeling comfortable in your own skin.',
                'First things first.',
                'Get out of yourself.',
                'G.O.D. - Good Orderly Direction.',
                'G.O.D. - Group Of Drunks.',
                'God doesn\'t give us what we want; God gives us what we need.',
                'Have an attitude of gratitude.',
                'H.O.W. - Honest, Open, and Willing.',
                'I can\'t; He Can; I think I\'ll let Him.',
                'I didn\'t get in trouble every time a drank; but every time I got in trouble I was drinking.',
                'I was sick and tired of being sick and tired.',
                'If I could drink like a normal person, I\'d drink every day.',
                'If nothing changes, nothing changes.',
                'If you are not completely satisfied with AA, your misery will be promptly refunded.',
                'If you don\'t drink, you won\'t get drunk.',
                'If you hang out in a barbershop, you just might get a haircut.',
                'Insanity is doing the same thing over and over again, expecting different results.',
                'It takes what it takes.',
                'It works if you work it.',
                'It\'s no fun having a belly full of alcohol, if you have a head full of AA.',
                'Keep coming back.',
                'Keep it simple.',
                'Let go and let God.',
                'Live and let Live.',
                'Look for the similarities, not at the differences.',
                'Meeting makers make it.',
                'No 13th stepping.',
                'One day at a time.',
                'Play the tape all the way through.',
                'Poor me, poor me, pour me another drink.',
                'Relapse is a process, not an event.',
                'Stick with the winners.',
                'Stinkin\' Thinkin\'',
                'Surrender to win.',
                'Take suggestions.',
                'Take the cotton out of your ears and put it in your mouth.',
                'The first step is the only one you have to work perfectly.',
                'There is only one thing you have to change - and that\'s everything.',
                'This is a program for people who want it, not for people who need it.',
                'This is a selfish program.',
                'This is a We program.',
                'This program is simple, not easy.',
                'This, too, shall pass.',
                'Trust the process.',
                'Turn it over.',
                'Wait a year.',
                'We are not bad people trying to get good, we are sick people trying to get well.',
                'We have a disease that tells us: we don\'t have a disease.',
                'When all else fails, working with another alcoholic saves the day.',
                'When you get hit by a train, it\'s not the caboose that kills you.',
                'While you work on recovery, your addiction is doing push ups.',
                'Work the steps.',
                'You can carry the message, you can\'t carry the alcoholic.',
                'You can\'t save your face and your ass at the same time.',
            ],
        }
    }
}
